/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.romangaranin.komido

import kotlin.test.Test

class KomidoTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Komido("NONE")
    }
}
